### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '<stdin>'

### ISSUE THREAD

**Issue by neoneo40** [lobocv/pyperform#1]
In [1]: from pyperform import BenchmarkedFunction

In [2]:

In [2]: def _setup():
   ...:         a = 10
   ...:

In [3]: @BenchmarkedFunction(setup=_setup, largs=(5,))
   ...: def multiply_by_a(b):
   ...:         result = a \* b
   ...:         assert result == 50
   ...:         return result
##    ...:

IOError                                   Traceback (most recent call last)
<ipython-input-3-a5675637ba6c> in <module>()
----> 1 @BenchmarkedFunction(setup=_setup, largs=(5,))
      2 def multiply_by_a(b):
      3         result = a \* b
      4         assert result == 50
      5         return result

/Users/re4lfl0w/.virtualenvs/general/lib/python2.7/site-packages/pyperform/**init**.pyc in **call**(self, caller)
    254     def **call**(self, caller):
    255         if self.enable:
--> 256             super(BenchmarkedFunction, self).**call**(caller)
    257             if not self.is_class_method:
    258                 self.run_timeit(self.stmt, self.setup_src)

/Users/re4lfl0w/.virtualenvs/general/lib/python2.7/site-packages/pyperform/**init**.pyc in **call**(self, caller)
    144
    145             fp = inspect.getfile(caller)
--> 146             imports = get_tagged_imports(fp, _import_tag)
    147             func_src = remove_decorators(globalize_indentation(inspect.getsource(caller)))
    148

/Users/re4lfl0w/.virtualenvs/general/lib/python2.7/site-packages/pyperform/**init**.pyc in get_tagged_imports(fp, tag)
     93
     94 def get_tagged_imports(fp, tag):
---> 95     with open(fp, 'r') as f:
     96         imports = [l[:l.index(tag)] for l in f if tag in l and (l.startswith('import') or l.startswith('from'))]
     97     src = '\n'.join(imports)

IOError: [Errno 2] No such file or directory: '<ipython-input-3-a5675637ba6c>'

**Comment by lobocv** [comment]
That is strange. It is trying to look for the tagged import statements in the script but it can't seem to find the script file. Are you running this script from a file or from the interpreter? When I run it, it works.
Can you confirm that you can run `inspect.getfile(your_script_path)` on your script? (you need to import inspect). In your debug info it looks like inspect.getfile(your_script_path)  is returning an empty string.

**Comment by neoneo40** [comment]
Thanks @lobocv .
I wrote pyperform_test.py then I success and get answer "multiply_by_a   228.723 ns".
But I tried first time in ipython notebook.
ok. I will use pyperform in command line.

**Comment by lobocv** [comment]
No problem :)
Thank you for pointing out that there may be issues when using the command line interpreter.
I will start thinking about ways around this.
